TACRED_LABELS =[
    "org:founded",
    "org:subsidiaries",
    "per:date_of_birth",
    "per:cause_of_death",
    "per:age",
    "per:stateorprovince_of_birth",
    "per:countries_of_residence",
    "per:country_of_birth",
    "per:stateorprovinces_of_residence",
    "org:website",
    "per:cities_of_residence",
    "per:parents",
    "per:employee_of",
    "No Relation",
    "per:city_of_birth",
    "org:parents",
    "org:political/religious_affiliation",
    "per:schools_attended",
    "per:country_of_death",
    "per:children",
    "org:top_members/employees",
    "per:date_of_death",
    "org:members",
    "org:alternate_names",
    "per:religion",
    "org:member_of",
    "org:city_of_headquarters",
    "per:origin",
    "org:shareholders",
    "per:charges",
    "per:title",
    "org:number_of_employees/members",
    "org:dissolved",
    "org:country_of_headquarters",
    "per:alternate_names",
    "per:siblings",
    "org:stateorprovince_of_headquarters",
    "per:spouse",
    "per:other_family",
    "per:city_of_death",
    "per:stateorprovince_of_death",
    "org:founded_by"
]

TACREV_LABELS = [
    'per:parents', 
    'org:founded', 
    'org:member_of', 
    'per:schools_attended', 
    'per:cause_of_death', 
    'per:date_of_birth', 
    'per:countries_of_residence', 
    'per:stateorprovinces_of_residence', 
    'per:charges', 
    'per:country_of_death', 
    'per:employee_of', 
    'org:members', 
    'org:stateorprovince_of_headquarters', 
    'org:dissolved', 
    'org:number_of_employees', 
    'per:title', 
    'per:stateorprovince_of_death', 
    'per:city_of_death', 
    'per:origin', 
    'per:age', 
    'org:shareholders', 
    'per:city_of_birth', 
    'per:date_of_death', 
    'org:website', 
    'org:political/religious_affiliation', 
    'per:siblings', 
    'no_relation', 
    'per:other_family', 
    'org:country_of_headquarters', 
    'per:cities_of_residence', 
    'per:spouse', 
    'org:employees', 
    'org:founded_by', 
    'org:alternate_names', 
    'per:stateorprovince_of_birth', 
    'org:city_of_headquarters', 
    'per:children', 
    'org:subsidiaries', 
    'per:alternate_names', 
    'org:parents', 
    'per:religion'
]

RETACRED_LABELS = [
    'per:origin', 
    'per:schools_attended', 
    'org:alternate_names', 
    'per:charges', 
    'per:city_of_death', 
    'org:founded', 
    'per:city_of_birth', 
    'per:religion', 
    'org:top_members/employees', 
    'org:stateorprovince_of_branch', 
    'org:members', 
    'org:dissolved', 
    'per:stateorprovinces_of_residence', 
    'per:age', 
    'per:cities_of_residence', 
    'org:city_of_branch', 
    'per:stateorprovince_of_death', 
    'per:identity', 
    #'no_relation', 
    'per:cause_of_death', 
    'per:spouse', 
    'per:stateorprovince_of_birth', 
    'org:shareholders', 
    'per:country_of_death', 
    'org:number_of_employees/members', 
    'org:website', 
    'org:member_of', 
    'per:date_of_death', 
    'per:countries_of_residence', 
    'per:date_of_birth', 
    'per:children', 
    'per:employee_of', 
    'per:other_family', 
    'per:siblings', 
    'org:country_of_branch', 
    'org:political/religious_affiliation', 
    'per:title', 
    'org:founded_by', 
    'per:parents'
]

RETACRED_NL_LABELS = [
    "Person's Origin",
    "Person's Schools Attended",
    "Organization's Alternate Names",
    "Person's Charges",
    "Person's City of Death",
    "Organization Founded",
    "Person's City of Birth",
    "Person's Religion",
    "Organization's Top Members/Employees",
    "Organization's State or Province of Branch",
    "Organization's Members",
    "Organization Dissolved",
    "Person's State or Provinces of Residence",
    "Person's Age",
    "Person's Cities of Residence",
    "Organization's City of Branch",
    "Person's State or Province of Death",
    "Person's Identity",
    #"(No Relation)",
    "Person's Cause of Death",
    "Person's Spouse",
    "Person's State or Province of Birth",
    "Organization's Shareholders",
    "Person's Country of Death",
    "Organization's Number of Employees/Members",
    "Organization's Website",
    "Organization Member Of",
    "Person's Date of Death",
    "Person's Countries of Residence",
    "Person's Date of Birth",
    "Person's Children",
    "Person Employee Of",
    "Person's Other Family",
    "Person's Siblings",
    "Organization's Country of Branch",
    "Organization's Political/Religious Affiliation",
    "Person's Title",
    "Organization Founded By",
    "Person's Parents",
]
